### ISSUE TITLE
9.1 errors

### ISSUE THREAD

**Issue by tailcat** [TheKrowi/Krowi_Addons#46]
223x WQAchievements\WQAchievements-v9.0.5-1.lua:2098: attempt to call field 'GetItemInfo' (a nil value)
[string "@WQAchievements\WQAchievements-v9.0.5-1.lua"]:2098: in function `IsTransmogable'
[string "@WQAchievements\WQAchievements-v9.0.5-1.lua"]:3318: in function `CheckMissions'
[string "@WQAchievements\WQAchievements-v9.0.5-1.lua"]:458: in function <WQAchievements\WQAchievements.lua:414>

Locals:
self = <table> {
 watched = <table> {
 }
 IsQuestFlaggedCompleted = <function> defined @WQAchievements\WQAchievements.lua:3379
 UpdateCustomRewards = <function> defined @WQAchievements\Options.lua:1508
 SetRewardLinkByID = <function> defined @WQAchievements\WQAchievements.lua:2955
 EnableModule = <function> defined @AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetRewardForID = <function> defined @WQAchievements\WQAchievements.lua:1678
 IterateEmbeds = <function> defined @AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 ToggleGet = <function> defined @WQAchievements\Options.lua:1292
 CreateCustomQuest = <function> defined @WQAchievements\Options.lua:1379
 debug = false
 isQuestPinActive = <function> defined @WQAchievements\WQAchievements.lua:3368
 slash = <function> defined @WQAchievements\WQAchievements.lua:468
 SetDefaultModulePrototype = <function> defined @AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 Show = <function> defined @WQAchievements\WQAchievements.lua:1525
 itemList = <table> {
 }
 defaultModuleState = true
 AnnouncePopUp = <function> defined @WQAchievements\WQAchievements.lua:2813
 IsEnabled = <function> defined @AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 ExpansionList = <table> {
 }
 ScheduleTimer = <function> defined @AckisRecipeList\libs\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 missionList = <table> {
 }
 CreateCustomMissionReward = <function> defined @WQAchievements\Options.lua:1638
 GetArgs = <function> defined @AckisRecipeList\libs\AceConsole-3.0\AceConsole-3.0.lua:144
 data = <table> {
 }
 CreateGroup = <function> defined @WQAchievements\Options.lua:1295
 start = 322493.403000
 questList = <table> {
 }
 ZoneIDList = <table> {
 }
 emissaryRewards = false
 EmissaryReward = <function> defined @WQAchievements\WQAchievements.lua:3054
 questPinMapList = <table> {
 }
 AddRewardToMission = <function> defined @WQAchievements\WQAchievements.lua:1437
 CreateCustomReward = <function> defined @WQAchievements\Options.lua:1497
 SetEnabledState = <function> defined @AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 IsTransmogable = <function> defined @WQAchievements\WQAchievements.lua:2083
 enabledState = true
 link = <function> defined @WQAchievements\WQAchievements.lua:1664
 playerName = "Taelarth-Arathor"
 rewards = false
 questPinList = <table> {
 }
 links = <table> {
 }
 event = <unnamed> {
 }
 IterateModules = <function> defined @AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 optionsFrame = <unnamed> {
 }
 faction = "Alliance"
 db = <table> {
 }
 baseName = "WQAchievements"
 SortOptions = <function> defined @WQAchievements\Options.lua:1700
 Reward = <function> defined @WQAchievements\WQAchievements.lua:1939
 CancelTimer = <function> defined @AckisRecipeList\libs\AceTimer-3.0\AceTimer-3.0.lua:147
 CheckWQ = <function> defined @WQAchievements\WQAchievements.lua:1536
 AddToys = <function> defined @WQAchievements\WQAchievements.lua:1378
 AddMounts = <function> defined @WQAchievements\WQAchievements.lua:1309
 OnInitialize = <function> defined @WQAchievements\WQAchievements.lua:277
 NewModule = <function> defined @AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 Disable = <function> defined @AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 CreateQTip = <function> defined @WQAchievements\WQAchievements.lua:2524
 AddPets = <function> defined

**Comment by TheKrowi** [comment]
I'm afraid this is the wrong addon repo. https://github.com/Urtgard/WQAchievements is the correct one.
https://www.curseforge.com/wow/addons/wqachievements.
